### ISSUE TITLE
Missing Test: before.test.js - Test last invocation

### ISSUE THREAD

**Issue by ManishManwani36** [commit-lab/lodasher#1]
Hi @obber, I came from your tech roadmap video to solve the lodash functions. Love this repo btw would love to add a few more questions to it! 

I found a missing test script in the `before.test.js` file. The index.js file mentioned the `before` HOF must return the result of the last invocation. I added the following test script and it worked fine:

```
it("should return the result of the last invocation", function () {
        const returnedFunction = lodasher.before(3, function (a, b) {
            return a + b;
        });

        const result1 = returnedFunction(1, 2);
        const result2 = returnedFunction(3, 4);
        const result3 = returnedFunction(5, 6);

        expect(result1).toBe(3);
        expect(result2).toBe(7);
        expect(result3).toBe(7);
});
```

**Comment by obber** [comment]
Perfect, can you submit a PR with that addition? I think that would be fine :) once it lands, I'll update the replit as well.

Really appreciate your contribution!

**Comment by ManishManwani36** [comment]
Thanks! Happy to submit a PR. Requesting permission to push a new branch + PR

**Comment by obber** [comment]
Can you fork the repo and then submit a PR from your fork to mine?

**Comment by ManishManwani36** [comment]
Oh yeah I can, sorry I didn't know you could fork and make a PR 😅
